2025-05-31 20:19:56,180 - ERROR - Command execution failed
Traceback (most recent call last):
  File "C:\Users\Prateek\lmhu\core\agent.py", line 13, in execute_commands
    return generate_ppt_doc(command_json)
  File "C:\Users\Prateek\lmhu\core\generator_ppt.py", line 565, in generate_ppt_doc
    _apply_text_box_animation_with_comtypes(filepath, 0, 0, "shape_build")
UnboundLocalError: local variable 'filepath' referenced before assignment
